package={name='hololens', version='0.0.0', edition='2021'}

[dependencies]
openxr='*'
wgpu={version='*', features=['spirv']}
wgpu-hal='*'
pollster='*'
d3d12='*'
winapi='*' #DXGI_FORMAT_*

[patch.crates-io]
openxr={path='../openxrs/openxr'}
wgpu={path='../wgpu/wgpu'}